begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(17);

insert into auth.users (id, email, raw_user_meta_data)
values
  ('b0000000-0000-4000-8000-000000000001', 'legal-admin-a@test.local', '{}'::jsonb),
  ('b0000000-0000-4000-8000-000000000002', 'legal-sales-a@test.local', '{}'::jsonb),
  ('b0000000-0000-4000-8000-000000000003', 'legal-admin-b@test.local', '{}'::jsonb),
  ('b0000000-0000-4000-8000-000000000004', 'legal-super@test.local', '{}'::jsonb);

insert into public.organizations (id, org_code, name)
values
  ('b1000000-0000-4000-8000-000000000001', 'legalorga', 'Legal Org A'),
  ('b1000000-0000-4000-8000-000000000002', 'legalorgb', 'Legal Org B');

insert into public.org_members (id, user_id, org_id, role, status)
values
  ('b2000000-0000-4000-8000-000000000001', 'b0000000-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000001', 'admin', 'active'),
  ('b2000000-0000-4000-8000-000000000002', 'b0000000-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000001', 'sales', 'active'),
  ('b2000000-0000-4000-8000-000000000003', 'b0000000-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000002', 'admin', 'active');

insert into public.super_admins (id, email)
values ('b0000000-0000-4000-8000-000000000004', 'legal-super@test.local');

insert into public.legal_acceptances (
  id, user_id, organization_id, document_key, document_version,
  content_hash, action_type, acceptance_source
)
values
  ('b3000000-0000-4000-8000-000000000001', 'b0000000-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000001', 'authorized_user_terms', '1.0', repeat('a', 64), 'agreed', 'first_login_gate'),
  ('b3000000-0000-4000-8000-000000000002', 'b0000000-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000001', 'crm_privacy_notice', '1.0', repeat('b', 64), 'acknowledged', 'first_login_gate'),
  ('b3000000-0000-4000-8000-000000000003', 'b0000000-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000002', 'authorized_user_terms', '1.0', repeat('c', 64), 'agreed', 'first_login_gate');

select ok(
  (select relrowsecurity from pg_catalog.pg_class where oid = 'public.legal_acceptances'::regclass),
  'RLS is enabled on legal acceptances'
);

select is(has_table_privilege('anon', 'public.legal_acceptances', 'SELECT'), false, 'Anonymous has no table read grant');
select is(has_table_privilege('authenticated', 'public.legal_acceptances', 'SELECT'), true, 'Authenticated users have the read grant');
select is(has_table_privilege('authenticated', 'public.legal_acceptances', 'INSERT'), false, 'Authenticated users cannot insert acceptances');
select is(has_table_privilege('authenticated', 'public.legal_acceptances', 'UPDATE'), false, 'Authenticated users cannot update acceptances');
select is(has_table_privilege('authenticated', 'public.legal_acceptances', 'DELETE'), false, 'Authenticated users cannot delete acceptances');

set local role authenticated;
select set_config('request.jwt.claim.sub', 'b0000000-0000-4000-8000-000000000002', true);
select is((select count(*)::integer from public.legal_acceptances), 1, 'A user can read only their own acceptance');
select throws_ok(
  $$insert into public.legal_acceptances (user_id, organization_id, document_key, document_version, content_hash, action_type)
    values ('b0000000-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000001', 'acceptable_use_policy', '1.0', repeat('d', 64), 'agreed')$$,
  '42501',
  null,
  'A browser-authenticated user cannot write an acceptance'
);
reset role;

set local role authenticated;
select set_config('request.jwt.claim.sub', 'b0000000-0000-4000-8000-000000000001', true);
select is((select count(*)::integer from public.legal_acceptances), 2, 'An Org A admin can read acceptance status for Org A members');
select is((select count(*)::integer from public.legal_acceptances where organization_id = 'b1000000-0000-4000-8000-000000000002'), 0, 'An Org A admin cannot read Org B acceptances');
reset role;

set local role authenticated;
select set_config('request.jwt.claim.sub', 'b0000000-0000-4000-8000-000000000004', true);
select is((select count(*)::integer from public.legal_acceptances), 3, 'An authorized super admin can read acceptance status across organizations');
reset role;

select ok(
  (select accepted_at is not null and created_at is not null from public.legal_acceptances where id = 'b3000000-0000-4000-8000-000000000001'),
  'Acceptance and creation timestamps are generated by the database'
);

select throws_ok(
  $$insert into public.legal_acceptances (user_id, organization_id, document_key, document_version, content_hash, action_type)
    values ('b0000000-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000001', 'authorized_user_terms', '1.0', repeat('d', 64), 'agreed')$$,
  '23505',
  null,
  'The same user, organization, document and version cannot be accepted twice'
);

select throws_ok(
  $$insert into public.legal_acceptances (user_id, organization_id, document_key, document_version, content_hash, action_type)
    values ('b0000000-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000001', 'bad_hash', '1.0', 'short', 'agreed')$$,
  '23514',
  null,
  'Content hashes must be 64 lowercase hexadecimal characters'
);

select throws_ok(
  $$insert into public.legal_acceptances (user_id, organization_id, document_key, document_version, content_hash, action_type)
    values ('b0000000-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000001', 'bad_action', '1.0', repeat('e', 64), 'consented')$$,
  '23514',
  null,
  'Action type is limited to agreed or acknowledged'
);

select throws_ok(
  $$insert into public.legal_acceptances (user_id, organization_id, document_key, document_version, content_hash, action_type, acceptance_source)
    values ('b0000000-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000001', 'bad_source', '1.0', repeat('f', 64), 'agreed', 'browser')$$,
  '23514',
  null,
  'Acceptance source is limited to reviewed server-side flows'
);

select throws_ok(
  $$delete from public.org_members where id = 'b2000000-0000-4000-8000-000000000002'$$,
  '23503',
  null,
  'Membership deletion cannot silently remove retained acceptance evidence'
);

select * from finish();
rollback;
