"use client";
import { useEffect, useState } from "react";
import { BoxesIcon, FolderTreeIcon, ReceiptTextIcon, TruckIcon } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ModuleHeader } from "./module-tabs";

type DashboardData = { counts: { suppliers: number; categories: number; materials: number; prices: number }; recentPrices: Array<{ id:string;unit_price:number;currency:string;quote_date:string;material:{material_code:string;material_description:string;unit_of_measure:string}|null;supplier:{company_name:string}|null }>; recentMaterials:Array<{id:string;material_code:string;material_description:string;updated_at:string;category:{category_name:string}|null;updatedBy:{full_name:string|null;email:string|null}|null}> };
const stats = [["suppliers","Total Suppliers",TruckIcon],["categories","Total Material Categories",FolderTreeIcon],["materials","Total Materials",BoxesIcon],["prices","Total Supplier Price Records",ReceiptTextIcon]] as const;
export function LibraryDashboard() { const [data,setData]=useState<DashboardData|null>(null); const [error,setError]=useState(""); useEffect(()=>{fetch("/api/org/supplier-price-library/dashboard",{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error);setData(p)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load dashboard"))},[]); return <div className="mx-auto max-w-7xl space-y-6"><ModuleHeader title="Supplier Price Library" description="Independent reference library for master materials and historical supplier pricing." />{error?<ErrorBox message={error}/>:null}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([key,label,Icon])=><Card key={key} size="sm"><CardContent className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{data?data.counts[key]:<Skeleton className="h-9 w-16"/>}</p></div><Icon className="size-8 text-muted-foreground"/></CardContent></Card>)}</div><div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Recently Added Prices</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Material</TableHead><TableHead>Supplier</TableHead><TableHead>Price</TableHead><TableHead>Quote Date</TableHead></TableRow></TableHeader><TableBody>{!data?<LoadingRows cols={4}/>:data.recentPrices.length?data.recentPrices.map(r=><TableRow key={r.id}><TableCell><p className="font-medium">{r.material?.material_code??"—"}</p><p className="max-w-64 truncate text-xs text-muted-foreground">{r.material?.material_description??"—"} · {r.material?.unit_of_measure??"—"}</p></TableCell><TableCell>{r.supplier?.company_name??"—"}</TableCell><TableCell className="font-medium tabular-nums">{r.currency} {Number(r.unit_price).toFixed(2)}</TableCell><TableCell>{date(r.quote_date)}</TableCell></TableRow>):<Empty cols={4}/>}</TableBody></Table></CardContent></Card><Card><CardHeader><CardTitle>Recently Updated Materials</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Material</TableHead><TableHead>Category</TableHead><TableHead>Updated</TableHead><TableHead>Updated By</TableHead></TableRow></TableHeader><TableBody>{!data?<LoadingRows cols={4}/>:data.recentMaterials.length?data.recentMaterials.map(r=><TableRow key={r.id}><TableCell><p className="font-medium">{r.material_code}</p><p className="max-w-64 truncate text-xs text-muted-foreground">{r.material_description}</p></TableCell><TableCell>{r.category?.category_name??"—"}</TableCell><TableCell>{date(r.updated_at)}</TableCell><TableCell>{r.updatedBy?.full_name??r.updatedBy?.email??"—"}</TableCell></TableRow>):<Empty cols={4}/>}</TableBody></Table></CardContent></Card></div></div> }
function LoadingRows({cols}:{cols:number}){return <>{Array.from({length:4}).map((_,i)=><TableRow key={i}><TableCell colSpan={cols}><Skeleton className="h-8 w-full"/></TableCell></TableRow>)}</>}; function Empty({cols}:{cols:number}){return <TableRow><TableCell colSpan={cols} className="py-10 text-center text-muted-foreground">No records yet.</TableCell></TableRow>}; function date(v:string){return new Intl.DateTimeFormat("en-CA",{dateStyle:"medium"}).format(new Date(v))}; function ErrorBox({message}:{message:string}){return <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">{message}</div>}
