-- Invoice requests bridge Sales and Accounts without treating a request as an invoice.

create table public.invoice_requests (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete restrict,
  request_number bigint generated by default as identity,
  job_id uuid not null,
  purchase_order_id uuid not null,
  invoice_id uuid,
  requested_by uuid references public.profiles(id) on delete set null,
  invoice_type text not null,
  amount_type text not null,
  amount_value numeric(14,2) not null,
  requested_amount numeric(14,2) not null,
  billing_description text not null,
  items_to_include text[] not null default '{}',
  comments_for_accounts text,
  status text not null default 'pending',
  -- Immutable billing context from the accepted PO/job at submission time.
  job_number_snapshot text,
  po_number_snapshot text not null,
  po_received_date_snapshot date not null,
  customer_name_snapshot text not null,
  project_name_snapshot text,
  quotation_number_snapshot text not null,
  revision_number_snapshot integer not null default 0,
  salesperson_snapshot text,
  customer_contact_snapshot text,
  po_total_snapshot numeric(14,2) not null,
  payment_terms_snapshot text,
  customer_tax_snapshot text,
  customer_address_snapshot text,
  billing_address_snapshot text,
  shipping_address_snapshot text,
  currency text not null default 'CAD',
  accounts_started_at timestamptz,
  closed_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null,
  unique (id, org_id),
  unique (org_id, request_number),
  constraint invoice_requests_job_fk foreign key (job_id, org_id)
    references public.jobs(id, org_id) on delete restrict,
  constraint invoice_requests_po_fk foreign key (purchase_order_id, org_id)
    references public.job_purchase_orders(id, org_id) on delete restrict,
  constraint invoice_requests_invoice_fk foreign key (invoice_id, org_id)
    references public.job_invoices(id, org_id) on delete restrict,
  constraint invoice_requests_type_check check (invoice_type in
    ('deposit', 'progress', 'final', 'change_order', 'credit_note')),
  constraint invoice_requests_amount_type_check check (amount_type in
    ('percentage', 'remaining_balance', 'fixed_amount')),
  constraint invoice_requests_status_check check (status in
    ('pending', 'under_review', 'invoice_created', 'sent_to_customer', 'paid', 'archived')),
  constraint invoice_requests_amounts_check check (amount_value >= 0 and requested_amount >= 0)
);

create index idx_invoice_requests_org_status on public.invoice_requests(org_id, status, created_at desc);
create index idx_invoice_requests_job on public.invoice_requests(job_id, created_at desc);
create index idx_invoice_requests_requester on public.invoice_requests(requested_by, created_at desc);

create table public.invoice_request_documents (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete restrict,
  invoice_request_id uuid not null,
  document_type text not null default 'supporting_document',
  file_name text not null,
  file_path text not null unique,
  file_size bigint not null,
  mime_type text not null,
  uploaded_by uuid references public.profiles(id) on delete set null,
  uploaded_at timestamptz not null default now(),
  constraint invoice_request_documents_request_fk foreign key (invoice_request_id, org_id)
    references public.invoice_requests(id, org_id) on delete restrict
);

create index idx_invoice_request_documents_request
  on public.invoice_request_documents(invoice_request_id, uploaded_at desc);

create table public.invoice_request_status_history (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete restrict,
  invoice_request_id uuid not null,
  previous_status text,
  new_status text not null,
  changed_by uuid references public.profiles(id) on delete set null,
  remarks text,
  changed_at timestamptz not null default now(),
  constraint invoice_request_history_request_fk foreign key (invoice_request_id, org_id)
    references public.invoice_requests(id, org_id) on delete restrict
);

create index idx_invoice_request_history_request
  on public.invoice_request_status_history(invoice_request_id, changed_at desc);

create table public.crm_notifications (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null,
  title text not null,
  message text,
  href text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index idx_crm_notifications_user on public.crm_notifications(org_id, user_id, read_at, created_at desc);

create or replace function public.record_invoice_request_status_change()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    insert into public.invoice_request_status_history
      (org_id, invoice_request_id, previous_status, new_status, changed_by)
    values
      (new.org_id, new.id, null, new.status, new.updated_by);
  elsif old.status is distinct from new.status then
    insert into public.invoice_request_status_history
      (org_id, invoice_request_id, previous_status, new_status, changed_by)
    values
      (new.org_id, new.id, old.status, new.status, new.updated_by);
  end if;
  return new;
end;
$$;

create trigger set_invoice_requests_updated_at before update on public.invoice_requests
for each row execute function public.set_updated_at();
create trigger record_invoice_request_status after insert or update of status on public.invoice_requests
for each row execute function public.record_invoice_request_status_change();

alter table public.invoice_requests enable row level security;
alter table public.invoice_request_documents enable row level security;
alter table public.invoice_request_status_history enable row level security;
alter table public.crm_notifications enable row level security;

create policy invoice_requests_member_read on public.invoice_requests for select to authenticated
using (public.is_super_admin() or public.is_active_org_member(org_id));
create policy invoice_request_documents_member_read on public.invoice_request_documents for select to authenticated
using (public.is_super_admin() or public.is_active_org_member(org_id));
create policy invoice_request_history_member_read on public.invoice_request_status_history for select to authenticated
using (public.is_super_admin() or public.is_active_org_member(org_id));
create policy crm_notifications_own_read on public.crm_notifications for select to authenticated
using (user_id = auth.uid() and public.is_active_org_member(org_id));

grant select on public.invoice_requests, public.invoice_request_documents,
  public.invoice_request_status_history, public.crm_notifications to authenticated;
grant all on public.invoice_requests, public.invoice_request_documents,
  public.invoice_request_status_history, public.crm_notifications to service_role;
grant usage, select on sequence public.invoice_requests_request_number_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit)
values ('invoice-request-documents', 'invoice-request-documents', false, 15728640)
on conflict (id) do update set file_size_limit = excluded.file_size_limit;

insert into public.permission_modules (module_key, display_name, sort_order)
values ('invoice_requests', 'Invoice Requests', 85)
on conflict (module_key) do update set display_name = excluded.display_name,
  sort_order = excluded.sort_order, is_active = true, updated_at = now();

with actions(action_key, display_name, sort_order) as (values
  ('view', 'View', 10), ('create', 'Submit Request', 20),
  ('edit', 'Edit Request', 30), ('process', 'Process Request', 40),
  ('archive', 'Archive / Close', 50), ('reopen', 'Reopen', 60),
  ('delete', 'Delete', 70)
)
insert into public.permission_definitions (module_id, action_key, display_name, sort_order)
select pm.id, actions.action_key, actions.display_name, actions.sort_order
from actions cross join public.permission_modules pm
where pm.module_key = 'invoice_requests'
on conflict (module_id, action_key) do update set display_name = excluded.display_name,
  sort_order = excluded.sort_order, is_active = true, updated_at = now();

insert into public.role_default_permissions (role_key, permission_id, allowed)
select roles.role_key, pd.id, false
from (values ('admin'), ('sales'), ('accountant')) roles(role_key)
join public.permission_modules pm on pm.module_key = 'invoice_requests'
join public.permission_definitions pd on pd.module_id = pm.id
on conflict (role_key, permission_id) do nothing;

with allowed(role_key, action_key) as (values
  ('sales', 'view'), ('sales', 'create'), ('sales', 'edit'),
  ('accountant', 'view'), ('accountant', 'edit'), ('accountant', 'process'),
  ('accountant', 'archive'),
  ('admin', 'view'), ('admin', 'create'), ('admin', 'edit'), ('admin', 'process'),
  ('admin', 'archive'), ('admin', 'reopen'), ('admin', 'delete')
)
update public.role_default_permissions rdp set allowed = true, updated_at = now()
from public.permission_definitions pd
join public.permission_modules pm on pm.id = pd.module_id
join allowed a on a.action_key = pd.action_key
where pm.module_key = 'invoice_requests' and rdp.permission_id = pd.id
  and rdp.role_key = a.role_key;
