import { createAdminClient } from "@/lib/supabase/admin";
import { isDuplicateError,jsonError,logDatabaseError,pagination,positiveInteger,requireSupplierPriceSession,safeSearch,text } from "@/lib/supplier-price-library/server";

type MaterialBody={category_id?:unknown;material_description?:unknown;size_specification?:unknown;grade_material_type?:unknown;unit_of_measure?:unknown;notes?:unknown;duplicated_from_material_id?:unknown};

export async function GET(request:Request){const auth=await requireSupplierPriceSession("view");if("response"in auth)return auth.response;const p=new URL(request.url).searchParams,search=safeSearch(p.get("search")??""),categoryId=p.get("category")??"",supplierId=p.get("supplier")??"",status=p.get("status")??"active",dateFrom=p.get("dateFrom")??"",dateTo=p.get("dateTo")??"",recent=p.get("recent")??"",sort=p.get("sort")??"material_code",direction=p.get("direction")==="desc"?"desc":"asc",page=positiveInteger(p.get("page"),1),pageSize=Math.min(positiveInteger(p.get("pageSize"),20),100),start=(page-1)*pageSize;if(!["active","archived","all"].includes(status))return jsonError("Invalid status filter",400);const admin=createAdminClient();let constrainedIds:string[]|null=null;
  if(search){const [cats,suppliers,quoteRows]=await Promise.all([admin.from("supplier_price_categories").select("id").eq("org_id",auth.session.org_id).ilike("category_name",`%${search}%`),admin.from("supplier_price_suppliers").select("id").eq("org_id",auth.session.org_id).ilike("company_name",`%${search}%`),admin.from("supplier_price_records").select("material_id").eq("org_id",auth.session.org_id).ilike("supplier_quote_number",`%${search}%`)]);const supplierIds=(suppliers.data??[]).map(x=>x.id);let supplierMaterialIds:string[]=[];if(supplierIds.length){const r=await admin.from("supplier_price_records").select("material_id").eq("org_id",auth.session.org_id).in("supplier_id",supplierIds);supplierMaterialIds=(r.data??[]).map(x=>x.material_id)}constrainedIds=Array.from(new Set([...(quoteRows.data??[]).map(x=>x.material_id),...supplierMaterialIds]));const categoryIds=(cats.data??[]).map(x=>x.id);const base=admin.from("supplier_price_materials").select("id").eq("org_id",auth.session.org_id);const ors=[`material_code.ilike.%${search}%`,`material_description.ilike.%${search}%`,`size_specification.ilike.%${search}%`,`grade_material_type.ilike.%${search}%`];if(categoryIds.length)ors.push(`category_id.in.(${categoryIds.join(",")})`);const direct=await base.or(ors.join(","));constrainedIds=Array.from(new Set([...constrainedIds,...((direct.data??[]).map(x=>x.id))]));}
  if(supplierId||dateFrom||dateTo){let priceQuery=admin.from("supplier_price_records").select("material_id").eq("org_id",auth.session.org_id);if(supplierId)priceQuery=priceQuery.eq("supplier_id",supplierId);if(dateFrom)priceQuery=priceQuery.gte("quote_date",dateFrom);if(dateTo)priceQuery=priceQuery.lte("quote_date",dateTo);const result=await priceQuery;const ids=Array.from(new Set((result.data??[]).map(x=>x.material_id)));constrainedIds=constrainedIds===null?ids:constrainedIds.filter(id=>ids.includes(id));}
  let query=admin.from("supplier_price_materials").select("id,material_code,category_id,material_description,size_specification,grade_material_type,unit_of_measure,notes,is_archived,duplicated_from_material_id,created_at,updated_at",{count:"exact"}).eq("org_id",auth.session.org_id);if(status!=="all")query=query.eq("is_archived",status==="archived");if(categoryId)query=query.eq("category_id",categoryId);if(constrainedIds!==null){if(!constrainedIds.length)return Response.json({materials:[],pagination:pagination(page,pageSize,0)});query=query.in("id",constrainedIds);}if(recent==="added")query=query.gte("created_at",new Date(Date.now()-30*86400000).toISOString());if(recent==="updated")query=query.gte("updated_at",new Date(Date.now()-30*86400000).toISOString());
  const dbSort=["material_code","material_description","created_at","updated_at"].includes(sort)?sort:"material_code";const result=await query.order(dbSort,{ascending:direction==="asc",nullsFirst:false}).order("id",{ascending:true}).range(start,start+pageSize-1);if(result.error){logDatabaseError("Unable to fetch materials",result.error);return jsonError("Unable to fetch materials",500)}const rows=result.data??[],ids=rows.map(x=>x.id),categoryIds=Array.from(new Set(rows.map(x=>x.category_id)));const [cats,latest]=await Promise.all([categoryIds.length?admin.from("supplier_price_categories").select("id,category_name,is_archived").eq("org_id",auth.session.org_id).in("id",categoryIds):Promise.resolve({data:[]}),ids.length?admin.from("supplier_price_latest_records").select("material_id,supplier_id,unit_price,currency,quote_date").eq("org_id",auth.session.org_id).in("material_id",ids):Promise.resolve({data:[]})]);const categoryMap=new Map((cats.data??[]).map(x=>[x.id,x]));const aggregates=new Map<string,{supplierIds:Set<string>;latest:string|null;lowest:Map<string,number>}>();for(const price of latest.data??[]){const current=aggregates.get(price.material_id)??{supplierIds:new Set<string>(),latest:null,lowest:new Map<string,number>()};current.supplierIds.add(price.supplier_id);if(!current.latest||price.quote_date>current.latest)current.latest=price.quote_date;const value=Number(price.unit_price),old=current.lowest.get(price.currency);if(old===undefined||value<old)current.lowest.set(price.currency,value);aggregates.set(price.material_id,current)}const materials=rows.map(row=>{const a=aggregates.get(row.id);return{...row,category:categoryMap.get(row.category_id)??null,supplier_count:a?.supplierIds.size??0,latest_price_date:a?.latest??null,lowest_latest_prices:Array.from(a?.lowest??new Map()).map(([currency,unit_price])=>({currency,unit_price}))}});if(sort==="lowest_latest_price")materials.sort((a,b)=>compareNullable(Math.min(...a.lowest_latest_prices.map(x=>x.unit_price)),Math.min(...b.lowest_latest_prices.map(x=>x.unit_price)),direction));if(sort==="most_recent_price")materials.sort((a,b)=>compareNullable(a.latest_price_date,b.latest_price_date,direction));return Response.json({materials,pagination:pagination(page,pageSize,result.count??0)});
}

export async function POST(request:Request){const auth=await requireSupplierPriceSession("edit");if("response"in auth)return auth.response;let body:MaterialBody;try{body=await request.json()}catch{return jsonError("Invalid request body",400)}return createMaterial(body,auth.session.org_id,auth.session.user.id)}

async function createMaterial(body:MaterialBody,orgId:string,userId:string){const categoryId=text(body.category_id,true),description=text(body.material_description,true),unit=text(body.unit_of_measure,true);if(!categoryId||!description||!unit)return jsonError("Category, material description, and unit of measure are required",400);const admin=createAdminClient();const {data:category}=await admin.from("supplier_price_categories").select("id,is_archived").eq("org_id",orgId).eq("id",categoryId).maybeSingle();if(!category)return jsonError("Category not found",400);if(category.is_archived)return jsonError("Archived categories cannot be selected for new materials",400);let duplicatedFrom:string|null=null;if(body.duplicated_from_material_id!==undefined){duplicatedFrom=text(body.duplicated_from_material_id);if(duplicatedFrom){const {data:source}=await admin.from("supplier_price_materials").select("id").eq("org_id",orgId).eq("id",duplicatedFrom).maybeSingle();if(!source)return jsonError("Source material not found",400)}}const payload={org_id:orgId,category_id:categoryId,material_description:description,size_specification:text(body.size_specification),grade_material_type:text(body.grade_material_type),unit_of_measure:unit,notes:text(body.notes),duplicated_from_material_id:duplicatedFrom,created_by:userId,updated_by:userId};const {data,error}=await admin.from("supplier_price_materials").insert(payload).select("id,material_code,category_id,material_description,size_specification,grade_material_type,unit_of_measure,notes,is_archived,duplicated_from_material_id,created_at,updated_at").single();if(error){if(isDuplicateError(error)){const existing=await findExistingMaterial(admin,orgId,payload);return jsonError("A matching material already exists in the Master Material Library.",409,{existingMaterialId:existing})}logDatabaseError("Unable to create material",error);return jsonError("Unable to create material",500)}return Response.json({material:data},{status:201})}

async function findExistingMaterial(admin:ReturnType<typeof createAdminClient>,orgId:string,payload:{category_id:string;material_description:string;size_specification:string|null;grade_material_type:string|null;unit_of_measure:string}){let q=admin.from("supplier_price_materials").select("id").eq("org_id",orgId).eq("category_id",payload.category_id).ilike("material_description",payload.material_description).ilike("unit_of_measure",payload.unit_of_measure);q=payload.size_specification?q.ilike("size_specification",payload.size_specification):q.is("size_specification",null);q=payload.grade_material_type?q.ilike("grade_material_type",payload.grade_material_type):q.is("grade_material_type",null);const {data}=await q.limit(1).maybeSingle();return data?.id??null}
function compareNullable(a:string|number|null,b:string|number|null,direction:string){const av=a===null||a===Infinity?null:a,bv=b===null||b===Infinity?null:b;if(av===null)return 1;if(bv===null)return-1;return(av<bv?-1:av>bv?1:0)*(direction==="asc"?1:-1)}
